# Generated by Django 3.0.4 on 2020-03-27 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Please enter correct value'), django.core.validators.MaxValueValidator(100, 'Please enter correct value')]),
        ),
    ]
