# Generated by Django 3.0.4 on 2020-04-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plane_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='airlineapp.Plane'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='airlineapp.Route'),
        ),
    ]
