# Generated by Django 3.0.4 on 2020-04-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0002_auto_20200402_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='food_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='airlineapp.Food_Name'),
        ),
    ]
